<a href="https://colab.research.google.com/github/KeshavFTW099/R_Programming/blob/main/Modelling_Linear_Log_InR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Build a Linear Regression model and a Logistic Regression model using the given
dataset. Evaluate both models using the test data. Use the Linear Regression model to
predict numerical quantities and use the Logistic Regression model to predict the
class/category of new observations.

In [38]:
library(readr)

gym_data <- read_csv("/content/gym_regression_classification_dataset_160.csv")

Rows: 160 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): Name, Exercise_Type, Fitness_Level
dbl (6): Member_ID, Height_cm, Weight_kg, BMI, Calorie_Intake, Weekly_Expend...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [39]:
gym_data <- read.csv("/content/gym_regression_classification_dataset_160.csv")

head(gym_data)
str(gym_data)
summary(gym_data)

  Member_ID Name   Height_cm Weight_kg BMI  Calorie_Intake Exercise_Type
1 1         Aarav  182.8     85.9      25.7 2721           Powerlifting
2 2         Vihaan 163.2     57.6      21.6 2864           Endurance
3 3         Aditya 177.1     91.3      29.1 2680           Strength
4 4         Arjun  188.3     50.5      14.2 2623           HIIT
5 5         Rahul  166.1     68.5      24.8 2790           Hypertrophy
6 6         Karan  169.0     75.9      26.6 2584           Hypertrophy
  Weekly_Expenditure Fitness_Level
1 3404               Fit
2 3717               Fit
3 3272               Fit
4 3305               Fit
5 2966               Fit
6 2783               Fit

'data.frame':	160 obs. of  9 variables:
 $ Member_ID         : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Name              : chr  "Aarav" "Vihaan" "Aditya" "Arjun" ...
 $ Height_cm         : num  183 163 177 188 166 ...
 $ Weight_kg         : num  85.9 57.6 91.3 50.5 68.5 75.9 72.8 63.8 67.9 65.1 ...
 $ BMI               : num  25.7 21.6 29.1 14.2 24.8 26.6 24.1 22.2 25.8 21.6 ...
 $ Calorie_Intake    : int  2721 2864 2680 2623 2790 2584 2649 2615 2560 2982 ...
 $ Exercise_Type     : chr  "Powerlifting" "Endurance" "Strength" "HIIT" ...
 $ Weekly_Expenditure: int  3404 3717 3272 3305 2966 2783 2753 3122 3233 3287 ...
 $ Fitness_Level     : chr  "Fit" "Fit" "Fit" "Fit" ...

   Member_ID             Name       Height_cm       Weight_kg
 Min.   :  1.00   Length   :160   Min.   :158.0   Min.   :48.80
 1st Qu.: 40.75   N.unique :160   1st Qu.:167.7   1st Qu.:64.10
 Median : 80.50   N.blank  :  0   Median :173.8   Median :70.75
 Mean   : 80.50   Min.nchar:  3   Mean   :173.2   Mean   :70.98
 3rd Qu.:120.25   Max.nchar:  9   3rd Qu.:177.6   3rd Qu.:77.12
 Max.   :160.00                   Max.   :190.0   Max.   :91.90
      BMI        Calorie_Intake   Exercise_Type Weekly_Expenditure
 Min.   :14.20   Min.   :2320   Length   :160   Min.   :2540
 1st Qu.:21.57   1st Qu.:2624   N.unique :  5   1st Qu.:2993
 Median :24.00   Median :2770   N.blank  :  0   Median :3220
 Mean   :23.77   Mean   :2780   Min.nchar:  4   Mean   :3231
 3rd Qu.:26.02   3rd Qu.:2926   Max.nchar: 12   3rd Qu.:3407
 Max.   :32.70   Max.   :3597                   Max.   :4450
   Fitness_Level
 Length   :160
 N.unique :  2
 N.blank  :  0
 Min.nchar:  3
 Max.nchar: 17

Preprocessing

In [40]:
gym_data$Exercise_Type <- as.factor(gym_data$Exercise_Type)
gym_data$Fitness_Level <- as.factor(gym_data$Fitness_Level)

colSums(is.na(gym_data))

         Member_ID               Name          Height_cm          Weight_kg
                 0                  0                  0                  0
               BMI     Calorie_Intake      Exercise_Type Weekly_Expenditure
                 0                  0                  0                  0
     Fitness_Level
                 0

Sampling for Modeling and Validation

In [41]:
set.seed(123)

train_index <- sample(
  1:nrow(gym_data),
  0.8 * nrow(gym_data)
)

train_data <- gym_data[train_index, ]
test_data <- gym_data[-train_index, ]

nrow(train_data)
nrow(test_data) #Split into training and testing data

[1] 128

[1] 32

**Linear Regression**

In [42]:
linear_model <- lm(
  Weekly_Expenditure ~ Height_cm + Weight_kg + BMI +
    Calorie_Intake + Exercise_Type,
  data = train_data
)

summary(linear_model)

Call:
lm(formula = Weekly_Expenditure ~ Height_cm + Weight_kg + BMI +
    Calorie_Intake + Exercise_Type, data = train_data)

Residuals:
    Min      1Q  Median      3Q     Max
-323.57  -86.85   -2.14   74.17  392.85

Coefficients:
                            Estimate Std. Error t value Pr(>|t|)
(Intercept)               -454.89903 1834.82218  -0.248 0.804619
Height_cm                    6.08447   10.64066   0.572 0.568527
Weight_kg                    2.64241   13.36714   0.198 0.843633
BMI                         18.99531   39.94478   0.476 0.635274
Calorie_Intake               0.84528    0.06754  12.515  < 2e-16 ***
Exercise_TypeHIIT         -204.55278   54.20783  -3.773 0.000252 ***
Exercise_TypeHypertrophy  -534.87767   44.09767 -12.129  < 2e-16 ***
Exercise_TypePowerlifting -350.08567   43.24416  -8.096 5.56e-13 ***
Exercise_TypeStrength     -412.02912   45.30875  -9.094 2.61e-15 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 130 on 119 degrees of freedom
Multiple R-squared:  0.8651,	Adjusted R-squared:  0.856
F-statistic:  95.4 on 8 and 119 DF,  p-value: < 2.2e-16

Predict numerical quantities

In [43]:
linear_pred <- predict(
  linear_model,
  test_data
)

head(linear_pred)

       2        3       10       18       20       28
3521.464 3269.992 3291.665 3098.333 2950.970 3093.464

In [44]:
rmse <- sqrt(
  mean(
    (test_data$Weekly_Expenditure - linear_pred)^2
  )
)

rmse #Evaluate the Linear Regression model

[1] 101.6401

In [45]:
r2 <- cor(
  test_data$Weekly_Expenditure,
  linear_pred
)^2

r2

[1] 0.8997377

In [46]:
data.frame(
  Actual = test_data$Weekly_Expenditure,
  Predicted = round(linear_pred, 2)
)

    Actual Predicted
2   3717   3521.46
3   3272   3269.99
10  3287   3291.67
18  3075   3098.33
20  3014   2950.97
28  3193   3093.46
33  3314   3411.74
48  3513   3413.65
49  3411   3196.05
55  2902   2942.97
56  3645   3651.23
59  3003   3046.09
68  3159   3047.37
70  3648   3880.60
73  2752   2910.32
75  3140   3276.55
77  3359   3261.47
80  3147   3272.54
84  2764   2668.54
85  3185   3222.14
101 2773   2830.43
112 3318   3267.12
114 3200   3091.73
115 2909   2894.40
116 3296   3308.46
122 3756   3667.50
124 3000   3014.06
125 2565   2551.80
128 3099   3218.54
130 3247   3333.14
135 3991   3932.44
149 2781   2887.47

**-----------Logistic Regression-----------**

In [47]:
logistic_model <- glm(
  Fitness_Level ~ Height_cm + Weight_kg + BMI +
    Calorie_Intake + Exercise_Type,
  data = train_data,
  family = binomial
)

summary(logistic_model)

Call:
glm(formula = Fitness_Level ~ Height_cm + Weight_kg + BMI + Calorie_Intake +
    Exercise_Type, family = binomial, data = train_data)

Coefficients:
                            Estimate Std. Error z value Pr(>|z|)
(Intercept)               -1.200e+02  5.694e+01  -2.108  0.03502 *
Height_cm                  6.850e-01  3.289e-01   2.083  0.03728 *
Weight_kg                 -7.870e-01  3.889e-01  -2.024  0.04299 *
BMI                        3.027e+00  1.202e+00   2.519  0.01178 *
Calorie_Intake            -6.269e-03  2.232e-03  -2.809  0.00497 **
Exercise_TypeHIIT         -1.902e+00  1.770e+00  -1.075  0.28252
Exercise_TypeHypertrophy   1.487e+00  1.369e+00   1.086  0.27753
Exercise_TypePowerlifting  2.654e-01  1.462e+00   0.182  0.85596
Exercise_TypeStrength      7.418e-01  1.481e+00   0.501  0.61648
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 139.39  on 127  degrees of freedom
Residual deviance:  74.25  on 119  degrees of freedom
AIC: 92.25

Number of Fisher Scoring iterations: 6

In [48]:
prob <- predict(
  logistic_model,
  test_data,
  type = "response"
)

predicted_class <- ifelse(
  prob >= 0.5,
  "Fit",
  "Needs_Improvement"
)

predicted_class <- factor(
  predicted_class,
  levels = levels(test_data$Fitness_Level)
)

head(predicted_class)

                2                 3                10                18
Needs_Improvement               Fit Needs_Improvement               Fit
               20                28
Needs_Improvement Needs_Improvement
Levels: Fit Needs_Improvement

In [49]:
confusion_matrix <- table(
  Actual = test_data$Fitness_Level,
  Predicted = predicted_class
)

confusion_matrix

                   Predicted
Actual              Fit Needs_Improvement
  Fit                 5                20
  Needs_Improvement   2                 5

In [50]:
accuracy <- mean(
  predicted_class == test_data$Fitness_Level
)

accuracy

[1] 0.3125

In [51]:
TP <- confusion_matrix["Fit", "Fit"]
FP <- confusion_matrix["Needs_Improvement", "Fit"]

precision <- TP / (TP + FP)

precision

[1] 0.7142857

In [52]:
FN <- confusion_matrix["Fit", "Needs_Improvement"]

recall <- TP / (TP + FN)

recall

[1] 0.2

Predict a New Observation

In [53]:
new_member <- data.frame(
  Height_cm = 175,
  Weight_kg = 72,
  BMI = 23.5,
  Calorie_Intake = 2600,
  Exercise_Type = factor(
    "Hypertrophy",
    levels = levels(gym_data$Exercise_Type)
  )
)

In [54]:
new_expenditure <- predict(
  linear_model,
  new_member
)

new_expenditure

       1
2909.371

In [55]:
new_probability <- predict(
  logistic_model,
  new_member,
  type = "response"
)

new_class <- ifelse(
  new_probability >= 0.5,
  "Fit",
  "Needs_Improvement"
)

new_probability
new_class

        1
0.3770298

                  1
"Needs_Improvement"